### ISSUE TITLE
Question: Is This Geared Towards Firebase Hosting?

### ISSUE THREAD

**Issue by alteredorange** [lpshanley/routify-starter-firebase#1] opened 2020-04-27 23:06 UTC
Hello! Curious about your starter template. Is it geared towards just Firebase hosting? Or getting different firebase modules to work with Routify on any hosting? I.e. Now and Netlify.

Thanks!

**Comment by lpshanley** [comment] 2020-06-29 18:47
This template is designed to provide an easy starting point for Firebase hosting with SSR using firebase functions already setup. It will use SSR on the initial load and then it will use hosting for all static files. Technically getting other modules to work isn't a part of this, is there a specific module you are troubleshooting?

**Comment by lpshanley** [comment] 2020-06-29 18:58
Duplicate of #2 
The solution for this will be in the other issue.

**Closed by lpshanley** 2020-06-29 18:58 UTC
Labels: question
